name: Build
on:
  workflow_dispatch:
jobs:
  release:
    name: Release - ${{ matrix.release_for }}
    strategy:
      matrix:
        include:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: simil
            name: simil-Linux-x86_64.tar.gz
            command: build
          #- release_for: Linux-aarch64
          #  os: ubuntu-latest
          #  target: aarch64-unknown-linux-gnu
          #  bin: simil
          #  name: simil-Linux-x86_64.tar.gz
          #  command: build
          #- release_for: Windows-x86_64
          #  os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #  bin: simil.exe
          #  name: simil-Windows-x86_64.zip
          #  command: build
          #- release_for: macOS-x86_64
          #  os: macOS-latest
          #  target: x86_64-apple-darwin
          #  bin: simil
          #  name: simil-Darwin-x86_64.tar.gz
          #  command: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.command }}
          target: ${{ matrix.target }}
          args: "--locked --release"
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ${{ matrix.name }} ${{ matrix.bin }}
          else
            tar czvf ${{ matrix.name }} ${{ matrix.bin }}
          fi
          cd -
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/${{ matrix.name }}
